language: node_js
sudo: false
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
cache:
  directories:
      - node_modules
after_script:
  - npm run test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a185b4ce88886181cec9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
